### ISSUE TITLE
Create a Logo for the New Manoa Gaming App

### ISSUE THREAD

**Issue by lenjason** [manoagaming/manoagaming#1]

**Comment by dcrelencia** [comment]
![manoagaminglogo1](https://user-images.githubusercontent.com/31523216/32581101-8f04e3a8-c48c-11e7-90a6-8f25e7656b62.png)
![manoagaminglogo2](https://user-images.githubusercontent.com/31523216/32581106-9543f04c-c48c-11e7-95ad-ca2ae6f3df4c.png)
![manoagaminglogo3](https://user-images.githubusercontent.com/31523216/32581173-d29345f6-c48c-11e7-9105-2e7fd3929b97.png)

**Comment by lenjason** [comment]
In class we voted for the third logo with some changes to the color scheme.

**Comment by dcrelencia** [comment]
![1manoagaming](https://user-images.githubusercontent.com/31523216/32928831-1fcc8140-caf8-11e7-9efb-6e5837a4fdaf.png)
![2manoagaming](https://user-images.githubusercontent.com/31523216/32928832-239c98dc-caf8-11e7-81fd-beb75c186614.png)

**Comment by jeremy-felipe** [comment]
I'm down for the second set of logos here. Overall, I think top logo is stronger, but I also lean towards the font on the second logo. I would say try see how the top logo looks with the bottom font and see if it looks g. 

Also, while it might mess with the contours on it, the top one's shading could be made to look like a U and an H. Might make it look weird, idk, but if it looks alright I think that'll look pretty damn good.

**Comment by dcrelencia** [comment]
<img width="421" alt="3manoa gaming" src="https://user-images.githubusercontent.com/31523216/32929698-f0c32ec0-cafd-11e7-9224-9586882f90bf.png">

**Comment by dcrelencia** [comment]
![manoagaming5](https://user-images.githubusercontent.com/31523216/33114154-a0a56218-ceff-11e7-871e-af68a0e8fd51.png)
